Bugfix: attribute naming consistency, drop_cols
scikit-learn-contrib/sklearn-pandas pull request #219
Opened 2020-09-23 14:34 UTC by VHeusinkveld

Within the scikit-learn ecosystem, it is standard practice to name the attributes like the init arguments. In this way the get_parms method can get the attributes. From sklearn version 24 onwards this is required behavior.

2020-09-23 14:38 UTC, VHeusinkveld commented
To eleborate on the issue: it is specifically concerned with the DataFrameMapper. It turned up when I embedded it in a scikit learn Pipeline. The warning can be found here: https://github.com/scikit-learn/scikit-learn/blob/0fb307bf3/sklearn/base.py#L209

2020-09-23 18:10 UTC, VHeusinkveld commented
The test seemed to have incorrectly passed in the past as in testing the get_params method is used. As the attribute name != argument name, the get_params for drop_cols would have returned non, and the object would not have been cloned correctly.

2020-09-23 18:34 UTC, VHeusinkveld commented
The problem is in the order of 

drop_cols or []

if the columns are empty the or statement will go for the second (which is a newly created list)
![image](https://user-images.githubusercontent.com/35037153/94054545-12e74400-fddc-11ea-9579-45305223ab03.png)

While if they are populated it goes for the first:
![image](https://user-images.githubusercontent.com/35037153/94054570-1bd81580-fddc-11ea-8e36-4511bc839868.png)

2020-09-23 18:52 UTC, VHeusinkveld commented
This fix does two things:
- Compatibility with scikit learn get_parms method associated with the base estimator (which caused a test to silently pass, this would be breaking behavior from sklearn 24 onwards)
- Solves an issue regarding cloning an object which has drop_cols == [ ].

2020-09-30 15:25 UTC, VHeusinkveld commented
@ragrawal could you review the code? 

It seems that the issue was introduced in PR #217

2020-10-01 00:47 UTC, ragrawal commented
@VHeusinkveld thanks for changes. Please let me review it by tomorrow and get back to you.

2020-10-01 00:58 UTC, ragrawal requested changes
Hi @VHeusinkveld 
Thanks for explaining the issue and fixing it . Can you please add your name to the list of contributors and bump the version number from 2.0.1 to 2.0.2 (in sklearn_pandas/__initi__.py)

Regards,
Ritesh

2020-10-01 00:58 UTC, ragrawal commented on sklearn_pandas/dataframe_mapper.py
> -        self.drop_columns = state.get('drop_cols', None)
It make sense to change the default from None to empty list ([]) here as well.

2020-10-01 09:58 UTC, VHeusinkveld reviewed
Changes look good!

2020-10-01 10:04 UTC, VHeusinkveld commented
@ragrawal all things should be updated now.

2020-10-01 20:33 UTC, ragrawal approved these changes

2020-10-01 20:33 UTC, merged